name: Alert Test

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Notification channel'
        required: true
        default: 'zapi'
        type: choice
        options:
          - zapi
      message:
        description: 'Test message'
        required: true
        default: 'TEST: CNAE Prospector alert pipeline is working.'
        type: string
      phone_override:
        description: 'Override destination phone (optional)'
        required: false
        type: string

jobs:
  notify-zapi:
    if: ${{ inputs.channel == 'zapi' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp test via Z-API
        env:
          ZAPI_INSTANCE_ID: ${{ secrets.ZAPI_INSTANCE_ID }}
          ZAPI_TOKEN: ${{ secrets.ZAPI_TOKEN }}
          ZAPI_DEFAULT_TO: ${{ secrets.ZAPI_TO }}
          MESSAGE: ${{ inputs.message }}
          PHONE_OVERRIDE: ${{ inputs.phone_override }}
        run: |
          if [ -z "${ZAPI_INSTANCE_ID}" ] || [ -z "${ZAPI_TOKEN}" ]; then
            echo "Z-API secrets not set."; exit 1; fi
          TO="${PHONE_OVERRIDE}"
          if [ -z "${TO}" ]; then TO="${ZAPI_DEFAULT_TO}"; fi
          if [ -z "${TO}" ]; then echo "Destination phone not set."; exit 1; fi
          BODY=$(jq -nc --arg phone "$TO" --arg message "$MESSAGE" '{phone:$phone, message:$message}')
          echo "Sending to $TO"
          curl -sS -X POST \
            -H 'Content-Type: application/json' \
            -d "$BODY" \
            "https://api.z-api.io/instances/${ZAPI_INSTANCE_ID}/token/${ZAPI_TOKEN}/send-text" || true

