name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Static checks (import smoke test)
        run: |
          python -m compileall -q src
          python - << 'PY'
          import sys
          sys.path.insert(0, '')
          import src.main
          print('Imported src.main OK')
          PY

      - name: Smoke test CLI help
        run: python src/main.py --help

  deploy-railway:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Conditional deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          if [ -z "${RAILWAY_TOKEN}" ]; then
            echo "RAILWAY_TOKEN not set. Skipping deploy."
            exit 0
          fi
          npm i -g @railway/cli
          railway status || true
          railway up --service cnae-prospector --ci || railway up --ci || true