name: Uptime Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check production health endpoint
        env:
          PROD_HEALTH_URL: https://cnae-prospector-production.up.railway.app/health
        run: |
          set -e
          URL="${PROD_HEALTH_URL}"
          echo "Checking ${URL}"
          for i in 1 2 3; do
            CODE=$(curl -sS -m 15 -w '%{http_code}' -o resp.json "${URL}" || true)
            echo "HTTP ${CODE}"
            cat resp.json || true
            if [ "${CODE}" = "200" ] && grep -q '"status"\s*:\s*"ok"' resp.json; then
              echo "Health OK"
              exit 0
            fi;
            echo "Retry ${i}..."; sleep 10
          done
          echo "Health check failed"
          exit 1

  notify-zapi:
    needs: healthcheck
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp alert via Z-API (if secrets present)
        env:
          ZAPI_INSTANCE_ID: ${{ secrets.ZAPI_INSTANCE_ID }}
          ZAPI_TOKEN: ${{ secrets.ZAPI_TOKEN }}
          ZAPI_TO: ${{ secrets.ZAPI_TO }}
          PROD_HEALTH_URL: https://cnae-prospector-production.up.railway.app/health
        run: |
          if [ -z "${ZAPI_INSTANCE_ID}" ] || [ -z "${ZAPI_TOKEN}" ] || [ -z "${ZAPI_TO}" ]; then
            echo "Z-API secrets not set; skipping WhatsApp notification."
            exit 0
          fi
          MSG="[CNAE-Prospector] Health check FAILED: ${PROD_HEALTH_URL} - $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          BODY=$(jq -nc --arg phone "${ZAPI_TO}" --arg message "${MSG}" '{phone: $phone, message: $message}')
          curl -sS -X POST \
            -H 'Content-Type: application/json' \
            -d "${BODY}" \
            "https://api.z-api.io/instances/${ZAPI_INSTANCE_ID}/token/${ZAPI_TOKEN}/send-text" || true

